variables:
- name: APP_VERSION
  value: '0.2.0'

pr: none

trigger:
  branches:
    include:
    - master

jobs:
- job: Buildltsc2019
  displayName: Build Windows version (ltsc2019)
  pool:
    vmImage: windows-2019
  steps:
  - template: scripts/steps/build-images.yml
    parameters:
      appVersion: ${{ variables.APP_VERSION }}
      osVersion: ltsc2019
- job: BuildUbuntu
  displayName: Build Linux version Ubuntu
  strategy:
    matrix:
      "18.04":
        UBUNTU_VERSION: "18.04"
      "20.04":
        UBUNTU_VERSION: "20.04"
  dependsOn:
    - Buildltsc2019
  pool:
    vmImage: ubuntu-20.04
  steps:
  - checkout: self
    clean: true
    persistCredentials: true
  - template: scripts/steps/build-images.yml
    parameters:
      appVersion: ${{ variables.APP_VERSION }}
      osVersion: ubuntu-$(UBUNTU_VERSION)
  - pwsh: |
      git tag $env:APP_VERSION
      git push origin $env:APP_VERSION
    workingDirectory: $(Build.Repository.LocalPath)
    displayName: Tag Github repository
