variables:
- name: APP_VERSION
  value: '0.0.1'

pr: none

trigger:
  branches:
    include:
    - master

jobs:
- job: Buildltsc2019
  displayName: Build Windows version (ltsc2019)
  pool:
    vmImage: windows-2019
  steps:
  - template: scripts/steps/build-images.yml
    parameters:
      appVersion: ${{ variables.APP_VERSION }}
      osVersion: ltsc2019
- job: BuildUbuntu1804
  displayName: Build Linux version (Ubuntu 18.04)
  pool:
    vmImage: ubuntu-18.04
  steps:
  - checkout: self
    clean: true
    persistCredentials: true
  - template: scripts/steps/build-images.yml
    parameters:
      appVersion: ${{ variables.APP_VERSION }}
      osVersion: ubuntu-18.04
  - pwsh: |
      git tag $env:APP_VERSION
      git push origin $env:APP_VERSION
    workingDirectory: $(Build.Repository.LocalPath)
    displayName: Tag Github repository
